apiList.push({
    "title":"缓存:清空所有缓存（限管理员）"
    ,"desc":""
    ,"time":""
    ,"action":"/cache/emptyCache"
    ,"method":"post"
    ,"request":[
    ]
});

apiList.push({
    "title":"缓存:缓存服务器状态（限管理员）"
    ,"desc":""
    ,"time":""
    ,"action":"/cache/info"
    ,"method":"get"
    ,"request":[
    ]
});
